import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart3,
  Droplets,
  GitBranch,
  LogIn,
  LogOut,
  Mountain,
  Settings,
  Shield,
  Spline,
  Square,
  Target,
  TrendingDown,
  TrendingUp,
} from "lucide-react";
import {
  createContradictingBranch,
  createDemandRangeChildren,
  createSupplyDemandOBIMChildren,
  createSupplyRangeChildren,
  customPrice,
} from "../tree.constants";
import type { TreeNode } from "../tree.utils";

export const ideaStrategyTree: TreeNode[] = [
  {
    key: "market_structure",
    title: "MS",
    icon: BarChart3,
    iconClassName: "",
    children: [
      {
        key: "swing",
        title: "Swing",
        icon: Activity,
        iconClassName: "",
        children: createContradictingBranch("swing", ["bullish", "bearish"]),
      },
      {
        key: "fractal",
        title: "Fractal",
        icon: GitBranch,
        iconClassName: "",
        children: createContradictingBranch("fractal", ["bullish", "bearish"]),
      },
      {
        key: "optional_settings",
        title: "_+_",
        icon: Settings,
        iconClassName: "",
        isDir: true,
        children: [
          {
            key: "protected_levels",
            title: "Protected",
            icon: Shield,
            iconClassName: "",
            children: [
              {
                key: "protected_high",
                anti: ["protected_low"],
                title: "High",
                icon: ArrowUp,
                iconClassName: "",
                inputField: customPrice(),
              },
              {
                key: "protected_low",
                anti: ["protected_high"],
                title: "Low",
                icon: ArrowDown,
                iconClassName: "",
                inputField: customPrice(),
              },
            ],
          },
          {
            key: "weak_levels",
            title: "Weak",
            icon: AlertTriangle,
            iconClassName: "",
            children: [
              {
                key: "weak_high",
                anti: ["weak_low"],
                title: "High",
                icon: ArrowUp,
                iconClassName: "",
                inputField: customPrice(),
              },
              {
                key: "weak_low",
                anti: ["weak_high"],
                title: "Low",
                icon: ArrowDown,
                iconClassName: "",
                inputField: customPrice(),
              },
            ],
          },
          {
            key: "market_structure_liquidity",
            title: "Liquidity",
            icon: Droplets,
            iconClassName: "",
            children: [
              {
                key: "wicking_tops",
                title: "Wicking Tops",
                icon: Mountain,
                iconClassName: "scale-x-[-1]",
              },
              {
                key: "wicking_bottoms",
                title: "Wicking Bottoms",
                icon: Mountain,
                iconClassName: "rotate-180",
              },
              {
                key: "liquidity_curve",
                title: "Curve",
                iconClassName: "",
                children: [
                  {
                    key: "liquidity_curve_up",
                    title: "Up",
                    icon: Spline,
                    iconClassName: "rotate-180 text-emerald-500",
                    anti: ["liquidity_curve_down"],
                  },
                  {
                    key: "liquidity_curve_down",
                    title: "Down",
                    icon: Spline,
                    iconClassName: "rotate-90 text-rose-500",
                    anti: ["liquidity_curve_up"],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: "entry",
    title: "Entry",
    icon: LogIn,
    iconClassName: "",
    children: [
      {
        key: "entry_demand",
        title: "Demand",
        icon: TrendingUp,
        iconClassName: "text-emerald-500",
        anti: ["entry_supply"],
        children: [
          {
            key: "entry_demand_range",
            title: "Range",
            icon: Square,
            iconClassName: "",
            children: createDemandRangeChildren("entry_demand"),
          },
          {
            key: "entry_demand_obim",
            title: "OBIM",
            icon: Target,
            iconClassName: "",
            children: createSupplyDemandOBIMChildren("entry_demand"),
          },
        ],
      },
      {
        key: "entry_supply",
        title: "Supply",
        icon: TrendingDown,
        iconClassName: "text-rose-500",
        anti: ["entry_demand"],
        children: [
          {
            key: "entry_supply_range",
            title: "Range",
            icon: Square,
            iconClassName: "",
            children: createSupplyRangeChildren("entry_supply"),
          },
          {
            key: "entry_supply_obim",
            title: "OBIM",
            icon: Target,
            iconClassName: "",
            children: createSupplyDemandOBIMChildren("entry_supply"),
          },
        ],
      },
    ],
  },
  {
    key: "exit",
    title: "Exit",
    icon: LogOut,
    iconClassName: "",
    children: [
      {
        key: "exit_demand",
        title: "Demand",
        icon: TrendingUp,
        iconClassName: "text-emerald-500",
        anti: ["exit_supply"],
        children: [
          {
            key: "exit_demand_range",
            title: "Range",
            icon: Square,
            iconClassName: "",
            children: createDemandRangeChildren("exit_demand"),
          },
          {
            key: "exit_demand_obim",
            title: "OBIM",
            icon: Target,
            iconClassName: "",
            children: createSupplyDemandOBIMChildren("exit_demand"),
          },
        ],
      },
      {
        key: "exit_supply",
        title: "Supply",
        icon: TrendingDown,
        iconClassName: "text-rose-500",
        anti: ["exit_demand"],
        children: [
          {
            key: "exit_supply_range",
            title: "Range",
            icon: Square,
            iconClassName: "",
            children: createSupplyRangeChildren("exit_supply"),
          },
          {
            key: "exit_supply_obim",
            title: "OBIM",
            icon: Target,
            iconClassName: "",
            children: createSupplyDemandOBIMChildren("exit_supply"),
          },
        ],
      },
    ],
  },
];
