import { Doc } from "../_generated/dataModel";

export const TRADING_ASSETS = [
  "BTCUSDT",
  "ETHUSDT",
  "BNBUSDT",
  "ADAUSDT",
  "DOTUSDT",
  "LINKUSDT",
  "LTCUSDT",
  "BCHUSDT",
  "XLMUSDT",
  "EOSUSDT",
  "TRXUSDT",
  "ETCUSDT",
  "XRPUSDT",
  "SOLUSDT",
  "AVAXUSDT",
  "MATICUSDT",
  "ATOMUSDT",
  "NEARUSDT",
  "ALGOUSDT",
  "VETUSDT",
  "FTMUSDT",
  "MANAUSDT",
  "SANDUSDT",
  "AXSUSDT",
  "SHIBUSDT",
  "DOGEUSDT",
  "GALAUSDT",
  "ENJUSDT",
  "CHZUSDT",
  "BATUSDT",
  // Forex pairs
  "EURUSD",
  "GBPUSD",
  "USDJPY",
  "AUDUSD",
  "USDCAD",
  "USDCHF",
  "NZDUSD",
  "EURJPY",
  "GBPJPY",
  "AUDJPY",
  "EURAUD",
  "EURGBP",
  "AUDCAD",
  "GBPAUD",
  // Stock symbols
  "AAPL",
  "GOOGL",
  "MSFT",
  "AMZN",
  "TSLA",
  "META",
  "NVDA",
  "NFLX",
  "BABA",
  "DIS",
  "PYPL",
  "ADBE",
  "CRM",
  "INTC",
  "AMD",
  "ORCL",
];

export const TIMEFRAMES = [
  "1m",
  "2m",
  "3m",
  "5m",
  "6m",
  "10m",
  "12m",
  "15m",
  "20m",
  "24m",
  "30m",
  "1h",
  "2h",
  "4h",
  "6h",
  "8h",
  "12h",
  "18h",
  "D",
  "2D",
  "3D",
  "4D",
  "5D",
  "6D",
  "W",
  "2W",
  "M",
];

export const TRADE_STATUSES: Doc<"snapshots">["status"][] = [
  "idea",
  "watching",
  "executed",
  "closed",
  "reviewed",
  "canceled",
] as const;
export const TRADE_DIRECTIONS = ["long", "short"] as const;

// Strategy-based titles for more realistic trade setups
export const STRATEGY_TEMPLATES = [
  "Breakout above resistance at {price}",
  "Pullback to {timeframe} support",
  "Flag pattern continuation",
  "Double bottom reversal setup",
  "Ascending triangle breakout",
  "Descending triangle breakdown",
  "Bull flag after {percent}% move",
  "Bear flag after rejection",
  "Hammer reversal at support",
  "Shooting star at resistance",
  "Engulfing pattern reversal",
  "Doji at key level",
  "Volume spike breakout",
  "Moving average bounce",
  "Fibonacci retracement entry",
  "Trend line break and retest",
  "Channel breakout setup",
  "Head and shoulders pattern",
  "Inverse head and shoulders",
  "Cup and handle formation",
  "Pennant continuation",
  "Wedge pattern break",
  "Gap fill opportunity",
  "Earnings run-up play",
  "News catalyst setup",
];

// Realistic tag categories for different trading aspects
export const TAG_CATEGORIES = {
  patterns: [
    "breakout",
    "breakdown",
    "reversal",
    "continuation",
    "flag",
    "pennant",
    "triangle",
    "wedge",
    "channel",
    "support",
    "resistance",
    "trendline",
  ],
  indicators: [
    "rsi-oversold",
    "rsi-overbought",
    "macd-bullish",
    "macd-bearish",
    "moving-average-cross",
    "volume-spike",
    "bollinger-squeeze",
    "stochastic-signal",
  ],
  market_structure: [
    "higher-highs",
    "lower-lows",
    "consolidation",
    "trending",
    "sideways",
    "accumulation",
    "distribution",
    "markup",
    "markdown",
  ],
  risk_management: [
    "tight-stop",
    "wide-stop",
    "trailing-stop",
    "partial-profit",
    "scale-out",
    "position-sizing",
    "r-multiple-favorable",
    "high-probability",
  ],
  market_conditions: [
    "high-volume",
    "low-volume",
    "volatile",
    "stable",
    "trending-market",
    "range-bound",
    "news-driven",
    "technical-setup",
    "fundamental-catalyst",
  ],
  psychology: [
    "fomo",
    "fear",
    "greed",
    "patience",
    "discipline",
    "emotional",
    "confident",
    "uncertain",
    "stressed",
    "calm",
  ],
};

export const TESTING_BASE_TITLES = [
  "Phoenix",
  "Wither",
  "Storm",
  "Viper",
  "Shadow",
  "Thunder",
  "Blaze",
  "Frost",
  "Titan",
  "Raven",
  "Crimson",
  "Ember",
  "Mystic",
  "Vortex",
  "Nexus",
  "Apex",
  "Zenith",
  "Quantum",
  "Cipher",
  "Prism",
];
