/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Trade_templateRouteRouteImport } from './routes/trade_template/route'
import { Route as Trade_onboardingRouteRouteImport } from './routes/trade_onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Trade_onboardingAttach_tradeRouteImport } from './routes/trade_onboarding/attach_trade'
import { Route as Trade_onboardingAdd_tradeRouteImport } from './routes/trade_onboarding/add_trade'
import { Route as Trade_onboardingAdd_timeframesRouteImport } from './routes/trade_onboarding/add_timeframes'
import { Route as Trade_onboardingAdd_templateRouteImport } from './routes/trade_onboarding/add_template'
import { Route as Trade_onboardingAdd_tagsRouteImport } from './routes/trade_onboarding/add_tags'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appDashboardTrade_templatesIndexRouteImport } from './routes/(app)/dashboard/trade_templates/index'
import { Route as appDashboardTrade_templatesTrade_templateRouteImport } from './routes/(app)/dashboard/trade_templates/trade_template'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Trade_templateRouteRoute = Trade_templateRouteRouteImport.update({
  id: '/trade_template',
  path: '/trade_template',
  getParentRoute: () => rootRouteImport,
} as any)
const Trade_onboardingRouteRoute = Trade_onboardingRouteRouteImport.update({
  id: '/trade_onboarding',
  path: '/trade_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Trade_onboardingAttach_tradeRoute =
  Trade_onboardingAttach_tradeRouteImport.update({
    id: '/attach_trade',
    path: '/attach_trade',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_tradeRoute =
  Trade_onboardingAdd_tradeRouteImport.update({
    id: '/add_trade',
    path: '/add_trade',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_timeframesRoute =
  Trade_onboardingAdd_timeframesRouteImport.update({
    id: '/add_timeframes',
    path: '/add_timeframes',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_templateRoute =
  Trade_onboardingAdd_templateRouteImport.update({
    id: '/add_template',
    path: '/add_template',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_tagsRoute =
  Trade_onboardingAdd_tagsRouteImport.update({
    id: '/add_tags',
    path: '/add_tags',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardTrade_templatesIndexRoute =
  appDashboardTrade_templatesIndexRouteImport.update({
    id: '/trade_templates/',
    path: '/trade_templates/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardTrade_templatesTrade_templateRoute =
  appDashboardTrade_templatesTrade_templateRouteImport.update({
    id: '/trade_templates/trade_template',
    path: '/trade_templates/trade_template',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trade_onboarding': typeof Trade_onboardingRouteRouteWithChildren
  '/trade_template': typeof Trade_templateRouteRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/trade_onboarding/add_tags': typeof Trade_onboardingAdd_tagsRoute
  '/trade_onboarding/add_template': typeof Trade_onboardingAdd_templateRoute
  '/trade_onboarding/add_timeframes': typeof Trade_onboardingAdd_timeframesRoute
  '/trade_onboarding/add_trade': typeof Trade_onboardingAdd_tradeRoute
  '/trade_onboarding/attach_trade': typeof Trade_onboardingAttach_tradeRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/dashboard/trade_templates/trade_template': typeof appDashboardTrade_templatesTrade_templateRoute
  '/dashboard/trade_templates': typeof appDashboardTrade_templatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trade_onboarding': typeof Trade_onboardingRouteRouteWithChildren
  '/trade_template': typeof Trade_templateRouteRoute
  '/about': typeof AboutRoute
  '/trade_onboarding/add_tags': typeof Trade_onboardingAdd_tagsRoute
  '/trade_onboarding/add_template': typeof Trade_onboardingAdd_templateRoute
  '/trade_onboarding/add_timeframes': typeof Trade_onboardingAdd_timeframesRoute
  '/trade_onboarding/add_trade': typeof Trade_onboardingAdd_tradeRoute
  '/trade_onboarding/attach_trade': typeof Trade_onboardingAttach_tradeRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/dashboard/trade_templates/trade_template': typeof appDashboardTrade_templatesTrade_templateRoute
  '/dashboard/trade_templates': typeof appDashboardTrade_templatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trade_onboarding': typeof Trade_onboardingRouteRouteWithChildren
  '/trade_template': typeof Trade_templateRouteRoute
  '/about': typeof AboutRoute
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/trade_onboarding/add_tags': typeof Trade_onboardingAdd_tagsRoute
  '/trade_onboarding/add_template': typeof Trade_onboardingAdd_templateRoute
  '/trade_onboarding/add_timeframes': typeof Trade_onboardingAdd_timeframesRoute
  '/trade_onboarding/add_trade': typeof Trade_onboardingAdd_tradeRoute
  '/trade_onboarding/attach_trade': typeof Trade_onboardingAttach_tradeRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/dashboard/trade_templates/trade_template': typeof appDashboardTrade_templatesTrade_templateRoute
  '/(app)/dashboard/trade_templates/': typeof appDashboardTrade_templatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trade_onboarding'
    | '/trade_template'
    | '/about'
    | '/dashboard'
    | '/trade_onboarding/add_tags'
    | '/trade_onboarding/add_template'
    | '/trade_onboarding/add_timeframes'
    | '/trade_onboarding/add_trade'
    | '/trade_onboarding/attach_trade'
    | '/dashboard/'
    | '/dashboard/trade_templates/trade_template'
    | '/dashboard/trade_templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trade_onboarding'
    | '/trade_template'
    | '/about'
    | '/trade_onboarding/add_tags'
    | '/trade_onboarding/add_template'
    | '/trade_onboarding/add_timeframes'
    | '/trade_onboarding/add_trade'
    | '/trade_onboarding/attach_trade'
    | '/dashboard'
    | '/dashboard/trade_templates/trade_template'
    | '/dashboard/trade_templates'
  id:
    | '__root__'
    | '/'
    | '/trade_onboarding'
    | '/trade_template'
    | '/about'
    | '/(app)/dashboard'
    | '/trade_onboarding/add_tags'
    | '/trade_onboarding/add_template'
    | '/trade_onboarding/add_timeframes'
    | '/trade_onboarding/add_trade'
    | '/trade_onboarding/attach_trade'
    | '/(app)/dashboard/'
    | '/(app)/dashboard/trade_templates/trade_template'
    | '/(app)/dashboard/trade_templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Trade_onboardingRouteRoute: typeof Trade_onboardingRouteRouteWithChildren
  Trade_templateRouteRoute: typeof Trade_templateRouteRoute
  AboutRoute: typeof AboutRoute
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade_template': {
      id: '/trade_template'
      path: '/trade_template'
      fullPath: '/trade_template'
      preLoaderRoute: typeof Trade_templateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade_onboarding': {
      id: '/trade_onboarding'
      path: '/trade_onboarding'
      fullPath: '/trade_onboarding'
      preLoaderRoute: typeof Trade_onboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade_onboarding/attach_trade': {
      id: '/trade_onboarding/attach_trade'
      path: '/attach_trade'
      fullPath: '/trade_onboarding/attach_trade'
      preLoaderRoute: typeof Trade_onboardingAttach_tradeRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_trade': {
      id: '/trade_onboarding/add_trade'
      path: '/add_trade'
      fullPath: '/trade_onboarding/add_trade'
      preLoaderRoute: typeof Trade_onboardingAdd_tradeRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_timeframes': {
      id: '/trade_onboarding/add_timeframes'
      path: '/add_timeframes'
      fullPath: '/trade_onboarding/add_timeframes'
      preLoaderRoute: typeof Trade_onboardingAdd_timeframesRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_template': {
      id: '/trade_onboarding/add_template'
      path: '/add_template'
      fullPath: '/trade_onboarding/add_template'
      preLoaderRoute: typeof Trade_onboardingAdd_templateRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_tags': {
      id: '/trade_onboarding/add_tags'
      path: '/add_tags'
      fullPath: '/trade_onboarding/add_tags'
      preLoaderRoute: typeof Trade_onboardingAdd_tagsRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/trade_templates/': {
      id: '/(app)/dashboard/trade_templates/'
      path: '/trade_templates'
      fullPath: '/dashboard/trade_templates'
      preLoaderRoute: typeof appDashboardTrade_templatesIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/trade_templates/trade_template': {
      id: '/(app)/dashboard/trade_templates/trade_template'
      path: '/trade_templates/trade_template'
      fullPath: '/dashboard/trade_templates/trade_template'
      preLoaderRoute: typeof appDashboardTrade_templatesTrade_templateRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
  }
}

interface Trade_onboardingRouteRouteChildren {
  Trade_onboardingAdd_tagsRoute: typeof Trade_onboardingAdd_tagsRoute
  Trade_onboardingAdd_templateRoute: typeof Trade_onboardingAdd_templateRoute
  Trade_onboardingAdd_timeframesRoute: typeof Trade_onboardingAdd_timeframesRoute
  Trade_onboardingAdd_tradeRoute: typeof Trade_onboardingAdd_tradeRoute
  Trade_onboardingAttach_tradeRoute: typeof Trade_onboardingAttach_tradeRoute
}

const Trade_onboardingRouteRouteChildren: Trade_onboardingRouteRouteChildren = {
  Trade_onboardingAdd_tagsRoute: Trade_onboardingAdd_tagsRoute,
  Trade_onboardingAdd_templateRoute: Trade_onboardingAdd_templateRoute,
  Trade_onboardingAdd_timeframesRoute: Trade_onboardingAdd_timeframesRoute,
  Trade_onboardingAdd_tradeRoute: Trade_onboardingAdd_tradeRoute,
  Trade_onboardingAttach_tradeRoute: Trade_onboardingAttach_tradeRoute,
}

const Trade_onboardingRouteRouteWithChildren =
  Trade_onboardingRouteRoute._addFileChildren(
    Trade_onboardingRouteRouteChildren,
  )

interface appDashboardRouteRouteChildren {
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appDashboardTrade_templatesTrade_templateRoute: typeof appDashboardTrade_templatesTrade_templateRoute
  appDashboardTrade_templatesIndexRoute: typeof appDashboardTrade_templatesIndexRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardIndexRoute: appDashboardIndexRoute,
  appDashboardTrade_templatesTrade_templateRoute:
    appDashboardTrade_templatesTrade_templateRoute,
  appDashboardTrade_templatesIndexRoute: appDashboardTrade_templatesIndexRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Trade_onboardingRouteRoute: Trade_onboardingRouteRouteWithChildren,
  Trade_templateRouteRoute: Trade_templateRouteRoute,
  AboutRoute: AboutRoute,
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
