/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as Trade_onboardingRouteRouteImport } from './routes/trade_onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Trade_onboardingAttach_tradeRouteImport } from './routes/trade_onboarding/attach_trade'
import { Route as Trade_onboardingAdd_tradeRouteImport } from './routes/trade_onboarding/add_trade'
import { Route as Trade_onboardingAdd_timeframesRouteImport } from './routes/trade_onboarding/add_timeframes'
import { Route as Trade_onboardingAdd_tagsRouteImport } from './routes/trade_onboarding/add_tags'
import { Route as LayoutTradeCardsRouteImport } from './routes/_layout.trade-cards'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Trade_onboardingRouteRoute = Trade_onboardingRouteRouteImport.update({
  id: '/trade_onboarding',
  path: '/trade_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Trade_onboardingAttach_tradeRoute =
  Trade_onboardingAttach_tradeRouteImport.update({
    id: '/attach_trade',
    path: '/attach_trade',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_tradeRoute =
  Trade_onboardingAdd_tradeRouteImport.update({
    id: '/add_trade',
    path: '/add_trade',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_timeframesRoute =
  Trade_onboardingAdd_timeframesRouteImport.update({
    id: '/add_timeframes',
    path: '/add_timeframes',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const Trade_onboardingAdd_tagsRoute =
  Trade_onboardingAdd_tagsRouteImport.update({
    id: '/add_tags',
    path: '/add_tags',
    getParentRoute: () => Trade_onboardingRouteRoute,
  } as any)
const LayoutTradeCardsRoute = LayoutTradeCardsRouteImport.update({
  id: '/trade-cards',
  path: '/trade-cards',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trade_onboarding': typeof Trade_onboardingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/trade-cards': typeof LayoutTradeCardsRoute
  '/trade_onboarding/add_tags': typeof Trade_onboardingAdd_tagsRoute
  '/trade_onboarding/add_timeframes': typeof Trade_onboardingAdd_timeframesRoute
  '/trade_onboarding/add_trade': typeof Trade_onboardingAdd_tradeRoute
  '/trade_onboarding/attach_trade': typeof Trade_onboardingAttach_tradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trade_onboarding': typeof Trade_onboardingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/trade-cards': typeof LayoutTradeCardsRoute
  '/trade_onboarding/add_tags': typeof Trade_onboardingAdd_tagsRoute
  '/trade_onboarding/add_timeframes': typeof Trade_onboardingAdd_timeframesRoute
  '/trade_onboarding/add_trade': typeof Trade_onboardingAdd_tradeRoute
  '/trade_onboarding/attach_trade': typeof Trade_onboardingAttach_tradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trade_onboarding': typeof Trade_onboardingRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/trade-cards': typeof LayoutTradeCardsRoute
  '/trade_onboarding/add_tags': typeof Trade_onboardingAdd_tagsRoute
  '/trade_onboarding/add_timeframes': typeof Trade_onboardingAdd_timeframesRoute
  '/trade_onboarding/add_trade': typeof Trade_onboardingAdd_tradeRoute
  '/trade_onboarding/attach_trade': typeof Trade_onboardingAttach_tradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trade_onboarding'
    | '/about'
    | '/dashboard'
    | '/trade-cards'
    | '/trade_onboarding/add_tags'
    | '/trade_onboarding/add_timeframes'
    | '/trade_onboarding/add_trade'
    | '/trade_onboarding/attach_trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trade_onboarding'
    | '/about'
    | '/dashboard'
    | '/trade-cards'
    | '/trade_onboarding/add_tags'
    | '/trade_onboarding/add_timeframes'
    | '/trade_onboarding/add_trade'
    | '/trade_onboarding/attach_trade'
  id:
    | '__root__'
    | '/'
    | '/trade_onboarding'
    | '/_layout'
    | '/about'
    | '/_layout/dashboard'
    | '/_layout/trade-cards'
    | '/trade_onboarding/add_tags'
    | '/trade_onboarding/add_timeframes'
    | '/trade_onboarding/add_trade'
    | '/trade_onboarding/attach_trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Trade_onboardingRouteRoute: typeof Trade_onboardingRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade_onboarding': {
      id: '/trade_onboarding'
      path: '/trade_onboarding'
      fullPath: '/trade_onboarding'
      preLoaderRoute: typeof Trade_onboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade_onboarding/attach_trade': {
      id: '/trade_onboarding/attach_trade'
      path: '/attach_trade'
      fullPath: '/trade_onboarding/attach_trade'
      preLoaderRoute: typeof Trade_onboardingAttach_tradeRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_trade': {
      id: '/trade_onboarding/add_trade'
      path: '/add_trade'
      fullPath: '/trade_onboarding/add_trade'
      preLoaderRoute: typeof Trade_onboardingAdd_tradeRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_timeframes': {
      id: '/trade_onboarding/add_timeframes'
      path: '/add_timeframes'
      fullPath: '/trade_onboarding/add_timeframes'
      preLoaderRoute: typeof Trade_onboardingAdd_timeframesRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/trade_onboarding/add_tags': {
      id: '/trade_onboarding/add_tags'
      path: '/add_tags'
      fullPath: '/trade_onboarding/add_tags'
      preLoaderRoute: typeof Trade_onboardingAdd_tagsRouteImport
      parentRoute: typeof Trade_onboardingRouteRoute
    }
    '/_layout/trade-cards': {
      id: '/_layout/trade-cards'
      path: '/trade-cards'
      fullPath: '/trade-cards'
      preLoaderRoute: typeof LayoutTradeCardsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface Trade_onboardingRouteRouteChildren {
  Trade_onboardingAdd_tagsRoute: typeof Trade_onboardingAdd_tagsRoute
  Trade_onboardingAdd_timeframesRoute: typeof Trade_onboardingAdd_timeframesRoute
  Trade_onboardingAdd_tradeRoute: typeof Trade_onboardingAdd_tradeRoute
  Trade_onboardingAttach_tradeRoute: typeof Trade_onboardingAttach_tradeRoute
}

const Trade_onboardingRouteRouteChildren: Trade_onboardingRouteRouteChildren = {
  Trade_onboardingAdd_tagsRoute: Trade_onboardingAdd_tagsRoute,
  Trade_onboardingAdd_timeframesRoute: Trade_onboardingAdd_timeframesRoute,
  Trade_onboardingAdd_tradeRoute: Trade_onboardingAdd_tradeRoute,
  Trade_onboardingAttach_tradeRoute: Trade_onboardingAttach_tradeRoute,
}

const Trade_onboardingRouteRouteWithChildren =
  Trade_onboardingRouteRoute._addFileChildren(
    Trade_onboardingRouteRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutTradeCardsRoute: typeof LayoutTradeCardsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutTradeCardsRoute: LayoutTradeCardsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Trade_onboardingRouteRoute: Trade_onboardingRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
